### ISSUE TITLE
下了几个之后经常会有error

### ISSUE THREAD

**Issue by jszgz** [wolfbolin/BiliUtil#21]
10/14 22:40:57 [ERROR] CUID#6 - Download aborted. URI=http://upos-hz-mirrorcosu.acgvideo.com/upgcxcode/28/18/28981828/28981828-2-64.flv?e=ig8euxZM2rNcNbhVhbUVhoMzhwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1571070234&gen=playurl&os=cosu&oi=3079040020&trid=52f7186f033e4b7eb8534d01a72ece6bu&platform=pc&upsig=c28554bec27647c333ff4d59342edc2e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=131739698
Exception: [AbstractCommand.cc:350] errorCode=19 URI=http://upos-hz-mirrorcosu.acgvideo.com/upgcxcode/28/18/28981828/28981828-2-64.flv?e=ig8euxZM2rNcNbhVhbUVhoMzhwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1571070234&gen=playurl&os=cosu&oi=3079040020&trid=52f7186f033e4b7eb8534d01a72ece6bu&platform=pc&upsig=c28554bec27647c333ff4d59342edc2e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=131739698
  -> [AbstractCommand.cc:800] errorCode=19 CUID#6 - Name resolution for upos-hz-mirrorcosu.acgvideo.com failed:Could not contact DNS servers

**Comment by wolfbolin** [comment]
从报错中就很容易看得出
`Could not contact DNS servers`
可能是B站的DNS服务没有正常解析，或者是你的服务商没有提供正确的服务

**Comment by jszgz** [comment]
> 从报错中就很容易看得出
> `Could not contact DNS servers`
> 可能是B站的DNS服务没有正常解析，或者是你的服务商没有提供正确的服务

下载一些视频到中途之后会报这个错，不知道为什么。错误意思我是能看懂

**Comment by jszgz** [comment]
就是某个视频下载百分比已经到一半的时候

**Comment by wolfbolin** [comment]
因为Aria采用的是多线程的下载，因此在这一过程中可能会出现连接断开或重连的问题。在需要重连时就自然需要DNS再次解析URL，因此你可能需要一个更稳定的宽带。
以后的版本也会逐渐尝试更加稳定的Aria配置，但是目前并没有更好的解决方案。

**Comment by jszgz** [comment]
刚才看了一下昨晚的的下载记录，从前几个成功之后后面的全都error了。。。。
dns有缓存，怎么会这次成功了下次就失败了呢。

**Comment by wolfbolin** [comment]
DNS连接失败也可能会报DNS异常的错误，请考虑修改一下你的DHCP服务器中配置的DNS，看看能不能解决问题。
另外，不知道你是什么平台，有些平台的底层库文件可能不依赖于系统的DNS缓存。

**Comment by jszgz** [comment]
我是ubuntu，是有系统缓存的。总之从报错来看很奇怪的问题。
