### ISSUE TITLE
设置Cookie后，执行下载后，一直卡在显示Cookie这边。

### ISSUE THREAD

**Issue by DaDaDa12138** [wolfbolin/BiliUtil#3]
![image](https://user-images.githubusercontent.com/16765962/53448889-5f368c00-39cd-11e9-8cf9-c2d463fa4dcd.png)

![image](https://user-images.githubusercontent.com/16765962/53448860-49c16200-39cd-11e9-9a92-fabbe71fdae9.png)

请问有什么解决办法吗？

**Comment by wolfbolin** [comment]
你的input函数用错啦,input括号内写的是输入提示。
你要从键盘输入内容，然后回车，输入的内容是input函数的返回值。
