### ISSUE TITLE
aria pull的时候如果有很多task的话  下载了十多条之后会有403的情况出现

### ISSUE THREAD

**Issue by john012343210** [wolfbolin/BiliUtil#38]
不知道能不能留个联系方式  一起讨论一下某些地方可以如何改善？

**Comment by wolfbolin** [comment]
这个问题可能不小心被我从QA中删去了，个人分析是因为视频链接中有鉴权参数，在过长时间没有下载时可能会出现参数失效的问题，目前代码中没有针对这个问题进行处理，但是在任务多或下载慢的情况下会出现这个问题。
可以联系我：mailto@wolfbolin.com

**Comment by john012343210** [comment]
this is difficult to solve i think
